### ISSUE TITLE
Terminal opens every time you open an app

### ISSUE THREAD

**Issue by ghost** [parabirb/sus93#3]
Currently, every time you open a package, it opens up a terminal window (this is only really necessary for the cli packages)
Maybe you can fix it by modifying the system a bit to know when to open a terminal and when to not open a terminal.

**Comment by parabirb** [comment]
sus93 is a thin wrapper around `le._apps`, so it'd take a bit of fiddling and would probably break the old packaging system.
it would probably be possible though, i'll see if there's a way to do it without breaking the old system

**Comment by parabirb** [comment]
if you're trying to launch apps from the gui thing you can just do `(eval(localStorage[".sus93/(app)"]))();` although that would probably break cli apps

**Comment by ghost** [comment]
Ill see what I can do.
