### ISSUE TITLE
fix compatibility with sus93-plus

### ISSUE THREAD

**Issue by parabirb** [parabirb/sus93#4]
@protogenraymond's sus93-plus requires patches for sus93 which shouldn't be necessary. i'll merge the patches into sus93 so that it works out of the box.

**Comment by ghost** [comment]
make sure you dm me when this issue is closed so i can remove the patch from the installation and not cause issues when installing sus93+

**Comment by parabirb** [comment]
ok

**Comment by nicejs-is-cool** [comment]
i made a pull request for this #5 it just applies all the patches sus93+ would have otherwise done

**Comment by parabirb** [comment]
merged
